### ISSUE TITLE
`toctree` directive missing in index.rst

### ISSUE THREAD

**Issue by choeppler** [hyperledger-labs/perun-doc#41]
Introduction cannot reached via navigation because toplevel `toctree` directive is missing.

**Comment by manoranjith** [comment]
Just noticed the same, will fix it in the next PR that adds a page for perun-node.

**Comment by choeppler** [comment]
@manoranjith, saw your comment a bit to late. I've already submitted a PR fixing this.

**Comment by manoranjith** [comment]
That is fine. I was doing the same fix, will merge your PR and merge the pending one.
