### ISSUE TITLE
👷 Switch from Circle CI to GitHub Actions

### ISSUE THREAD

**Issue by matthiasgeihs** [hyperledger-labs/perun-doc#66]
Problem:
The log of Circle CI runs cannot be viewed without registering with Circle CI. This basically forces developers to register with Circle CI, which requires granting write access to repositories, which in turn seems totally unjustified for just being able to view CI log output.

Solution:
Use GitHub Actions instead of Circle CI.

**Comment by manoranjith** [comment]
When were setting up the CI for this project, a couple of years ago, we found the features and maturity of Circle CI to be more suitable.

Now that, GitHub Actions is also mature, has comparable features and integrates better into the repository, I think we can switch to GitHub Actions.

**Comment by matthiasgeihs** [comment]
Closed in #76
